import {PLANET_DEFS,COLLECTORS,TERRAFORM_COST,LASER_COST,LASER_DAMAGE,POWER_CAP,makeGame,planet,beamLinks,powerOutput,objective,launchFleet,terraform,laserPulse,rotateCollector,aimCollector,waitTurn} from './game-core.js';
const $=id=>document.getElementById(id);let state=makeGame(new URLSearchParams(location.search).get('mode')==='optics'?'optics':'frontier'),source='eos',target=null,menuPlanet=null,awaitingDestination=false,fleetAmount=9,feedback=new URLSearchParams(location.search).get('mode')==='optics'?'Four receivers are already online. Route one collector to each distinct world.':'';
const map=$('map'),nodes=$('planetNodes');
function start(mode){state=makeGame(mode);const url=new URL(location);if(mode==='optics')url.searchParams.set('mode','optics');else url.searchParams.delete('mode');history.replaceState(null,'',url);source='eos';target=null;menuPlanet=null;awaitingDestination=false;fleetAmount=9;feedback=mode==='optics'?'Four receivers are already online. Route one collector to each distinct world.':'Eos is stable. Click Eos, then choose Launch from Eos.';render();}
function mapLines(){const links=beamLinks(state),parts=['<ellipse cx="500" cy="325" rx="84" ry="63" class="star-orbit"/>','<ellipse cx="500" cy="325" rx="350" ry="238" class="system-orbit"/>'];for(const link of links){const collector=COLLECTORS.find(c=>c.id===link.collector),p=planet(state,link.target);if(!p)continue;parts.push(`<line x1="${collector.x*10}" y1="${collector.y*6.5}" x2="${p.x*10}" y2="${p.y*6.5}" class="beam ${link.active?'active':'inactive'}"/>`);}for(const f of state.fleets){const a=planet(state,f.from),b=planet(state,f.to),progress=(f.total-f.eta+.5)/f.total,x=(a.x+(b.x-a.x)*progress)*10,y=(a.y+(b.y-a.y)*progress)*6.5;parts.push(`<line x1="${a.x*10}" y1="${a.y*6.5}" x2="${b.x*10}" y2="${b.y*6.5}" class="fleet-path"/><path d="M${x-8} ${y+7}L${x+10} ${y}L${x-8} ${y-7}Z" class="fleet-marker"/>`);}return parts.join('');}
function renderMap(){nodes.replaceChildren(...state.planets.map(p=>{const b=document.createElement('button');b.type='button';b.className=`planet ${p.owner} ${p.terraform?'terraformed':'unformed'} ${p.id===target?'targeted':''} ${p.id===source?'source':''} ${awaitingDestination&&p.id!==source?'destination-choice':''}`;b.dataset.planetId=p.id;b.style.left=p.x+'%';b.style.top=p.y+'%';b.style.setProperty('--planet-color',p.color);b.setAttribute('aria-label',`${p.name}, ${p.owner}, ${p.terraform?'terraformed':'not terraformed'}, ${p.ships} ships. ${awaitingDestination&&p.id!==source?'Choose as fleet destination.':'Open planet actions.'}`);b.innerHTML=`<span class="planet-core"></span><span class="planet-name">${p.name}</span><span class="planet-ships">${p.ships}</span>`;b.onclick=event=>{event.stopPropagation();openPlanetMenu(p.id);};return b;}));$('routes').innerHTML=mapLines();$('flightReadout').textContent=state.fleets.length?state.fleets.map(f=>`${f.ships} → ${planet(state,f.to).name} · ${f.eta}t`).join('  •  '):'No fleets in transit';}
function renderControls(){
 const src=planet(state,source),frontier=state.mode==='frontier'&&!state.won;
 $('sourceName').textContent=src?`${src.name} · ${src.ships} ships`:'No fleet source';
 $('orderHint').textContent=state.mode==='optics'?'Click a terraformed planet to aim compatible collectors from its action wheel.':awaitingDestination?`Fleet from ${src.name}: click a destination planet, then confirm the route and ship count.`:'Click one of your worlds and choose Launch from that world. Then click the destination.';
 $('destinationPrompt').hidden=!awaitingDestination;
 $('launchSourceName').textContent=src?.name??'';
 map.classList.toggle('choosing-destination',awaitingDestination);
 $('wait').hidden=state.mode==='optics';$('wait').disabled=!frontier||awaitingDestination;
}
function beginLaunch(id){source=id;awaitingDestination=true;menuPlanet=null;target=null;feedback=`Fleet from ${planet(state,id).name}: choose a destination planet.`;render();}
function cancelLaunch(){awaitingDestination=false;menuPlanet=null;target=null;feedback='Fleet order cancelled. Click one of your worlds to launch again.';render();}
function openPlanetMenu(id){
 if(awaitingDestination&&id===source){menuPlanet=null;target=null;feedback='Choose a different planet as the destination, or cancel this fleet order.';render();return;}
 menuPlanet=id;target=id;render();requestAnimationFrame(()=>$('planetMenu').querySelector('.menu-action:not(:disabled),.menu-close')?.focus());
}
function closePlanetMenu(){const previous=menuPlanet;menuPlanet=null;target=null;$('planetMenu').hidden=true;renderMap();requestAnimationFrame(()=>nodes.querySelector(`[data-planet-id="${previous}"]`)?.focus());}
function renderPlanetMenu(){
 const menu=$('planetMenu'),p=planet(state,menuPlanet);
 if(!p||state.won){menu.hidden=true;return;}
 menu.hidden=false;menu.setAttribute('aria-label',awaitingDestination?`Confirm fleet destination ${p.name}`:`Actions for ${p.name}`);menu.replaceChildren();
 const close=document.createElement('button');close.type='button';close.className='menu-close';close.textContent='×';close.setAttribute('aria-label','Close planet actions');close.onclick=closePlanetMenu;menu.append(close);
 const orbit=document.createElement('div');orbit.className='menu-orbit';
 const center=document.createElement('div');center.className='menu-center';
 const title=document.createElement('strong');title.textContent=p.name;
 const status=document.createElement('small');status.textContent=`${p.ships} ships · ${p.owner==='player'?(p.id===source?'fleet source':p.terraform?'receiver online':'foothold'):p.owner}`;
 center.append(title,status);orbit.append(center);
 const actions=[];
 if(awaitingDestination){
  const src=planet(state,source);
  actions.push({label:`Send to ${p.name}`,hint:`From ${src.name} to ${p.name}`,disabled:src.ships<1,run:()=>{const result=launchFleet(state,source,p.id,fleetAmount);if(result.ok)awaitingDestination=false;act(result);}});
 }else{
  if(state.mode==='frontier'){
   if(p.owner==='player')actions.push({label:`Launch from ${p.name}`,hint:'Choose a destination next',disabled:p.ships<1,run:()=>beginLaunch(p.id)});
   if(p.owner==='player'&&!p.terraform)actions.push({label:`Terraform · ${TERRAFORM_COST}`,hint:'Build shipyard and receiver',disabled:state.power<TERRAFORM_COST,run:()=>act(terraform(state,p.id))});
   if(p.owner==='rival')actions.push({label:`SOL laser · ${LASER_COST}`,hint:`Remove ${LASER_DAMAGE} defenders`,disabled:state.power<LASER_COST,run:()=>{const result=laserPulse(state,p.id);if(result.ok){map.classList.remove('pulse');void map.offsetWidth;map.classList.add('pulse');}act(result);}});
  }
  if(p.owner==='player'&&p.terraform)for(const def of COLLECTORS.filter(c=>c.options.includes(p.id)))actions.push({label:`Aim ${def.name.split(' / ')[0].split('-')[0]} ${def.name.split(' / ')[1]}`,hint:`${def.name} · ${def.yield} output`,run:()=>act(aimCollector(state,def.id,p.id))});
 }
 actions.forEach((item,i)=>{const button=document.createElement('button');button.type='button';button.className='menu-action';button.textContent=item.label;button.title=item.hint;button.disabled=!!item.disabled;const angle=-Math.PI/2+i*2*Math.PI/actions.length;button.style.left=`${50+Math.cos(angle)*33.3}%`;button.style.top=`${50+Math.sin(angle)*33.3}%`;button.onclick=item.run;orbit.append(button);});menu.append(orbit);
 const footer=document.createElement('div');footer.className='menu-footer';
 if(awaitingDestination){
  const src=planet(state,source);const route=document.createElement('strong');route.className='menu-route';route.textContent=`${src.name} → ${p.name}`;footer.append(route);
  const label=document.createElement('label');label.textContent='Ships to send: ';
  const count=document.createElement('output');const slider=document.createElement('input');slider.type='range';slider.min='1';slider.max=String(Math.max(1,src.ships));fleetAmount=Math.max(1,Math.min(fleetAmount,src.ships||1));slider.value=String(fleetAmount);count.textContent=String(fleetAmount);slider.oninput=()=>{fleetAmount=Number(slider.value);count.textContent=slider.value;};label.append(count,slider);footer.append(label);
 }else{const hint=document.createElement('span');hint.textContent=state.mode==='optics'?(p.owner==='player'&&p.terraform?'Aim a compatible collector at this receiver.':'This world has no online receiver.'):p.owner==='player'?p.blurb:'To send a fleet here, first choose Launch from one of your worlds.';footer.append(hint);}
 menu.append(footer);
 const width=menu.offsetWidth,height=menu.offsetHeight,x=p.x/100*map.clientWidth,y=p.y/100*map.clientHeight,pad=4;
 menu.style.left=`${Math.max(width/2+pad,Math.min(map.clientWidth-width/2-pad,x))}px`;
 menu.style.top=`${Math.max(height/2+pad,Math.min(map.clientHeight-height/2-pad,y))}px`;
}
function renderCollectors(){const links=beamLinks(state);$('collectors').replaceChildren(...COLLECTORS.map((def,i)=>{const link=links[i],b=document.createElement('button');b.type='button';b.className='collector '+(link.active?'linked':'offline');b.disabled=state.won;b.setAttribute('aria-label',`${def.name}, aiming at ${planet(state,link.target).name}, ${link.reason}, ${def.yield} possible power. Click to rotate.`);b.innerHTML=`<span class="collector-icon">✦</span><span><strong>${def.name}</strong><small>To ${planet(state,link.target).name} · ${link.reason}</small></span><b>${link.active?'+':''}${link.active?def.yield:0}</b>`;b.onclick=()=>act(rotateCollector(state,def.id));return b;}));}
function render(){if(state.won)awaitingDestination=false;const o=objective(state);$('turn').textContent=String(state.turn).padStart(2,'0');$('worlds').textContent=`${o.worlds} / ${o.requiredWorlds}`;$('power').textContent=state.power;$('output').textContent=`${o.output} / ${o.requiredOutput}`;$('goal').textContent=state.mode==='optics'?'Aim for 80 power output':'Four worlds + 75 output';$('unlockKicker').textContent=state.mode==='optics'?'OPTICS SIMULATION':'CAMPAIGN UNLOCK';$('unlockTitle').textContent=state.mode==='optics'?'4 RECEIVERS':'EOS ONLINE';$('unlockSub').textContent=state.mode==='optics'?'Light routing challenge · no fleets':'1 terraformed world · stellar map revealed';$('announcement').textContent=feedback||state.log[0];$('frontierMode').classList.toggle('selected',state.mode==='frontier');$('opticsMode').classList.toggle('selected',state.mode==='optics');renderControls();renderMap();renderCollectors();renderPlanetMenu();$('log').replaceChildren(...state.log.map(message=>{const li=document.createElement('li');li.textContent=message;return li;}));$('victory').hidden=!state.won;if(state.won){$('victoryTitle').textContent=state.mode==='optics'?'The light paths align.':'The stellar network expands.';$('victoryText').textContent=state.mode==='optics'?'Four separate planet receivers now take the full 82 units from the test collectors.':'Four terraformed worlds and at least 75 units of stellar output have opened the next campaign layer.';}}
function act(result){feedback=result.message;if(result.ok){menuPlanet=null;target=null;}render();}
function populateRules(){const values={terraformCost:TERRAFORM_COST,laserCost:LASER_COST,laserDamage:LASER_DAMAGE,powerCap:POWER_CAP,frontierWorlds:objective(makeGame('frontier')).requiredWorlds,frontierOutput:objective(makeGame('frontier')).requiredOutput,opticsOutput:objective(makeGame('optics')).requiredOutput};for(const element of document.querySelectorAll('[data-rule]'))element.textContent=values[element.dataset.rule];$('collectorRules').replaceChildren(...COLLECTORS.map(def=>{const row=document.createElement('tr');for(const value of [def.name,def.yield+' units',def.options.map(id=>PLANET_DEFS.find(p=>p.id===id).name).join(' → ')]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}return row;}));}
function showTab(tab,updateUrl=true){const rules=tab==='rules';$('playPanel').hidden=rules;$('rulesPanel').hidden=!rules;$('gameContext').hidden=rules;if(rules){menuPlanet=null;$('planetMenu').hidden=true;}for(const [id,selected] of [['playTab',!rules],['rulesTab',rules]]){const button=$(id);button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;}if(updateUrl){const url=new URL(location);if(rules)url.searchParams.set('tab','rules');else{url.searchParams.delete('tab');if(url.hash.startsWith('#rules-'))url.hash='';}history.replaceState(null,'',url);}if(updateUrl)$('gameTabs').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
$('playTab').onclick=()=>showTab('play');$('rulesTab').onclick=()=>showTab('rules');$('heroRules').onclick=()=>showTab('rules');$('returnGame').onclick=()=>showTab('play');$('gameTabs').onkeydown=event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='ArrowLeft'||event.key==='Home'?'play':'rules';showTab(next);$(next==='play'?'playTab':'rulesTab').focus();};populateRules();showTab(new URLSearchParams(location.search).get('tab')==='rules'||location.hash.startsWith('#rules-')?'rules':'play',false);if(location.hash.startsWith('#rules-'))requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());else if(new URLSearchParams(location.search).get('tab')==='rules')requestAnimationFrame(()=>$('gameTabs').scrollIntoView());
$('frontierMode').onclick=()=>start('frontier');$('opticsMode').onclick=()=>start('optics');$('reset').onclick=()=>start(state.mode);$('playAgain').onclick=()=>start(state.mode);$('wait').onclick=()=>act(waitTurn(state));$('cancelLaunch').onclick=cancelLaunch;map.onclick=event=>{if(!event.target.closest('.planet-menu'))closePlanetMenu();};$('planetMenu').onclick=event=>event.stopPropagation();document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menuPlanet)closePlanetMenu();});window.addEventListener('resize',()=>{if(menuPlanet)renderPlanetMenu();});render();
